import logging
import re
import time
from typing import Dict

from app.hooks.registry import HookContext, HookDefinition

logger = logging.getLogger(__name__)

# In-memory rate limit tracking (per chat_id)
_rate_limit_store: Dict[int, list] = {}


async def execute_log_messages(context: HookContext, hook: HookDefinition):
    """Log every message exchange."""
    logger.info(
        f"[MESSAGE] chat={context.chat_id} "
        f"user=\"{context.user_message[:80]}\" "
        f"response_len={len(context.response)} "
        f"skills={context.skills_used} "
        f"sources={len(context.sources)}"
    )


async def execute_token_counter(context: HookContext, hook: HookDefinition):
    """Track approximate token usage."""
    input_chars = sum(len(m.get("content", "")) for m in context.llm_messages)
    output_chars = len(context.response)
    input_tokens = input_chars // 4
    output_tokens = output_chars // 4
    logger.info(
        f"[TOKENS] input={input_tokens} output={output_tokens} "
        f"total={input_tokens + output_tokens} chat={context.chat_id}"
    )


async def execute_latency_tracker(context: HookContext, hook: HookDefinition):
    """Record start time (pre_message) — duration calculated in post_message."""
    context.metadata["start_time"] = time.time()


async def execute_latency_post(context: HookContext, hook: HookDefinition):
    """Calculate and log latency. Runs as part of log_messages post_message."""
    start = context.metadata.get("start_time")
    if start:
        duration = time.time() - start
        logger.info(f"[LATENCY] chat={context.chat_id} duration={duration:.2f}s")


async def execute_query_logger(context: HookContext, hook: HookDefinition):
    """Log skill selection results."""
    logger.info(
        f"[SKILLS] chat={context.chat_id} "
        f"selected={context.skills_used} "
        f"sources={len(context.sources)} "
        f"context_parts={len(context.context_parts)}"
    )


async def execute_profanity_filter(context: HookContext, hook: HookDefinition):
    """Basic profanity filter — block messages with bad words."""
    # Minimal demo list — replace with proper moderation in production
    bad_words = ["badword1", "badword2"]  # placeholder
    msg_lower = context.user_message.lower()
    for word in bad_words:
        if word in msg_lower:
            context.blocked = True
            context.blocked_reason = "Message contains inappropriate content"
            return


async def execute_rate_limiter(context: HookContext, hook: HookDefinition):
    """Rate limit: max 10 messages per minute per chat."""
    max_per_minute = 10
    now = time.time()
    chat_id = context.chat_id

    if chat_id not in _rate_limit_store:
        _rate_limit_store[chat_id] = []

    # Clean old timestamps
    _rate_limit_store[chat_id] = [
        t for t in _rate_limit_store[chat_id] if now - t < 60
    ]

    if len(_rate_limit_store[chat_id]) >= max_per_minute:
        context.blocked = True
        context.blocked_reason = "Rate limit exceeded. Please wait a moment."
        return

    _rate_limit_store[chat_id].append(now)


async def execute_add_disclaimer(context: HookContext, hook: HookDefinition):
    """Append AI disclaimer to response."""
    disclaimer = "\n\n---\n*This response was generated by AI and may contain inaccuracies. Please verify important information.*"
    context.modifications["response_append"] = disclaimer


async def execute_response_formatter(context: HookContext, hook: HookDefinition):
    """Clean up markdown formatting."""
    response = context.response
    if not response:
        return
    # Remove excessive newlines
    response = re.sub(r'\n{3,}', '\n\n', response)
    # Trim trailing whitespace per line
    response = '\n'.join(line.rstrip() for line in response.split('\n'))
    context.modifications["response_replace"] = response


def register_all_hook_executors(registry) -> None:
    """Register all built-in hook executors."""
    registry.register_executor("log_messages", execute_log_messages)
    registry.register_executor("token_counter", execute_token_counter)
    registry.register_executor("latency_tracker", execute_latency_tracker)
    registry.register_executor("query_logger", execute_query_logger)
    registry.register_executor("profanity_filter", execute_profanity_filter)
    registry.register_executor("rate_limiter", execute_rate_limiter)
    registry.register_executor("add_disclaimer", execute_add_disclaimer)
    registry.register_executor("response_formatter", execute_response_formatter)
